### ISSUE TITLE
Add "nodejs-mobile-react-native" properly

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite-new#3]
["nodejs-mobile-react-native"](https://github.com/janeasystems/nodejs-mobile-react-native) dependency has additional `postInstall` script inside which creates "nodejs-assest" dir with some files on the project root instead of workspace root (packages/native)

To archive this goal i was trying to use ["nohoist"](https://yarnpkg.com/blog/2018/02/15/nohoist/) settings in the root `package.json`

``` javascript
"workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/nodejs-mobile-react-native/**",
      "**/nodejs-mobile-react-native"
    ]
  },
```
But then `react-native` gets installed in multiple places (root/node_modules; packages/native/node_modules...) and `metro` and `haste-map` bundler throws compile errors about Duplicate Module Name: react-native or react-animated (depending on configuration)

If i run it as it is (with "nodejs-assest" on project root) this dir will not be copied to application assets and throws runtime error ("nodejs-assest/main.js" not found)

I was trying several combination (for example adding "react-native" to nohoist, like they have it on their [examples](https://yarnpkg.com/blog/2018/02/15/nohoist/) - with no luck

**Comment by szymonlesisz** [comment]
not that according to "nodejs-mobile-react-native" [install](https://github.com/janeasystems/nodejs-mobile-react-native#installation) you need to install few more system dependency (Android NDK and ninja) also `react-native link nodejs-mobile-react-native` needs to be called

**Comment by steida** [comment]
I pushed "naive" approach with nohoist for nodejs-mobile-react-native. To make it work, just delete duplicate packages/native/react-native. Otherwise, Metro bundler will fail.

We need to figure out how force Metro bundler to ignore second React Native, or how to force yarn to not install it, or add custom post install which will delete it.

Also, I am not sure how to cope with nodejs-assest npm dependencies. Are they supposed to be included in package? If so, we should probably consider https://github.com/zeit/pkg or https://github.com/zeit/ncc to minimize build.

**Comment by steida** [comment]
Another approach is "nohoist": ["**/react-native", "**/react-native/**"] from official yarn documentation https://github.com/connectdotz/yarn-nohoist-examples/tree/master/workspaces-examples/react-native but then we would have to use default React Native project. Maybe it's even better solution because React Native is duplicated (not sure why) anyway.

**Comment by steida** [comment]
Abd this should work but don't https://github.com/facebook/react-native/issues/21242#issuecomment-445784118

**Comment by szymonlesisz** [comment]
still an issue, heres what i did:
1. git pull
2. yarn deps (to be sure that i don't have any mess in node_modules)*
* this step rewrites both files `packages/native/nodejs-assets/build-native-modules-MacOS-helper-script-*` so if your solution were somewhere there, it's gone now
3. rm -rf ./packages/native/node_modules/react-native/
4. rm -rf ./packages/native/android/app/build (to be sure that i will get clean build)
5. yarn dev-android

Result: an error in build
```
> Task :app:transformNativeLibsWithMergeJniLibsForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/x86/libc++_shared.so'
```

If i skip 3 step (removing native/node_modules/react-native) app will build sucessfuly but then i get metro bundler error:
```
Loading dependency graph, done.
Error: Unable to resolve module `./packages/native/index` from `[...]/packages/native/.`: The module `./packages/native/index` could not be found from `[...]/packages/native/.`. Indeed, none of these files exist:
```

**Comment by szymonlesisz** [comment]
I've fixed it.
The reason was that `/native/package.json` scripts was using `react-native` from `/native/node_modules` and also `projectRoot` was not set at all.
Thats why `blacklistRE` wasn't work for you (in fact whole metro.config was ignored)

Moving `metro.config` to the root of the project + updating `/native/package.json` scripts solved this issue

**Comment by steida** [comment]
I saw it. Brilliant work.

**Comment by muhammadwfa** [comment]
Hi @szymonlesisz 
where can I find this directory /native/package.json
I have issue please help me
